yarnPath: ".yarn/releases/yarn-berry.cjs"
npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: false
    npmAuthToken: "8f0ed7eb354c0170205e06dbb0be720e9a006579"
npmScopes:
  strdstnet:
    npmRegistryServer: "https://npm.pkg.github.com"
  strdst:
    npmRegistryServer: "https://npm.pkg.github.com"
