npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: false
    npmAuthToken: 8f0ed7eb354c0170205e06dbb0be720e9a006579

npmScopes:
  strdst:
    npmRegistryServer: "https://npm.pkg.github.com"
  strdstnet:
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
