apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stardust
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: stardust
    spec:
      containers:
      - name: stardust
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 19132
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
